<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
    <EnableSourceLink>false</EnableSourceLink>
    <DebugType>portable</DebugType>
    <EmbedAllSources>false</EmbedAllSources>
		<UserSecretsId>KMCEventPlatform-Api-Development</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>

		<!-- Object-to-object mapping -->
		<PackageReference Include="AutoMapper"
						  Version="16.2.0" />

		<!-- JWT authentication -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"
						  Version="10.0.9" />

		<!-- Built-in ASP.NET Core OpenAPI generation -->
		<PackageReference Include="Microsoft.AspNetCore.OpenApi"
						  Version="10.0.9" />

		<!-- Secure OpenAPI.NET 2.x version -->
		<PackageReference Include="Microsoft.OpenApi"
						  Version="2.7.5" />

		<!-- Entity Framework Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore"
						  Version="10.0.9" />

		<!-- SQL Server / LocalDB provider -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"
						  Version="10.0.9" />

		<!-- Required for migrations and design-time operations -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design"
						  Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
		</PackageReference>

		<!-- Visual Studio Package Manager Console EF commands -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools"
						  Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers
			</IncludeAssets>
		</PackageReference>

		<!-- Scalar API documentation -->
		<PackageReference Include="Scalar.AspNetCore"
						  Version="2.16.11" />

	</ItemGroup>


</Project>