// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Organizer.Api.Data;

#nullable disable

namespace Organizer.Api.Migrations;

[DbContext(typeof(OrganizerDbContext))]
partial class OrganizerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerEvent", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<TimeSpan>("EndTime").HasColumnType("time");
            b.Property<DateTime>("EventDate").HasColumnType("datetime2");
            b.Property<DateTime>("EndDate").HasColumnType("datetime2");
            b.Property<string>("EventType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ExternalEventCode").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<bool>("IsPublished").HasColumnType("bit");
            b.Property<bool>("IsPublishedToKmc").HasColumnType("bit");
            b.Property<int?>("KmcEventId").HasColumnType("int");
            b.Property<string>("KmcSyncError").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("OrganizerName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<DateTime?>("PublishedToKmcAt").HasColumnType("datetime2");
            b.Property<TimeSpan>("StartTime").HasColumnType("time");
            b.Property<string>("Title").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("Venue").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.HasKey("Id");
            b.HasIndex("ExternalEventCode").IsUnique();
            b.ToTable("Events");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerTicketTier", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("Capacity").HasColumnType("int");
            b.Property<string>("Description").HasMaxLength(180).HasColumnType("nvarchar(180)");
            b.Property<int>("EventId").HasColumnType("int");
            b.Property<string>("Name").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
            b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
            b.Property<int>("SortOrder").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("EventId", "Name").IsUnique();
            b.ToTable("TicketTiers");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerBooking", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("BookingReference").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
            b.Property<string>("BookingSource").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CustomerEmail").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<string>("CustomerName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("CustomerPhone").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<int>("EventId").HasColumnType("int");
            b.Property<int>("Quantity").HasColumnType("int");
            b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<int>("TicketTierId").HasColumnType("int");
            b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
            b.Property<decimal>("UnitPrice").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
            b.HasKey("Id");
            b.HasIndex("BookingReference").IsUnique();
            b.HasIndex("EventId");
            b.HasIndex("TicketTierId");
            b.ToTable("Bookings");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerPayment", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
            b.Property<int>("BookingId").HasColumnType("int");
            b.Property<string>("CardBrand").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<string>("CardHolderName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("CardLastFour").IsRequired().HasMaxLength(4).HasColumnType("nvarchar(4)");
            b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("nvarchar(3)");
            b.Property<DateTime>("PaidAt").HasColumnType("datetime2");
            b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<string>("TransactionReference").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
            b.HasKey("Id");
            b.HasIndex("BookingId").IsUnique();
            b.HasIndex("TransactionReference").IsUnique();
            b.ToTable("Payments");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerTicketTier", b =>
        {
            b.HasOne("Organizer.Api.Entities.OrganizerEvent", "Event")
                .WithMany("TicketTiers")
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Event");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerBooking", b =>
        {
            b.HasOne("Organizer.Api.Entities.OrganizerEvent", "Event")
                .WithMany("Bookings")
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("Organizer.Api.Entities.OrganizerTicketTier", "TicketTier")
                .WithMany("Bookings")
                .HasForeignKey("TicketTierId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("Event");
            b.Navigation("TicketTier");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerPayment", b =>
        {
            b.HasOne("Organizer.Api.Entities.OrganizerBooking", "Booking")
                .WithOne("Payment")
                .HasForeignKey("Organizer.Api.Entities.OrganizerPayment", "BookingId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Booking");
        });

        modelBuilder.Entity("Organizer.Api.Entities.OrganizerEvent", b =>
        {
            b.Navigation("Bookings");
            b.Navigation("TicketTiers");
        });
        modelBuilder.Entity("Organizer.Api.Entities.OrganizerTicketTier", b => b.Navigation("Bookings"));
        modelBuilder.Entity("Organizer.Api.Entities.OrganizerBooking", b => b.Navigation("Payment"));
#pragma warning restore 612, 618
    }
}
