// <auto-generated />
using System;
using KMC.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KMC.Api.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260721150000_AddTicketingAndDemoPayments")]
partial class AddTicketingAndDemoPayments
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("KMC.Api.Entities.Event", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                b.Property<int>("Id"));

            b.Property<int>("Capacity").HasColumnType("int");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Description")
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");
            b.Property<TimeSpan>("EndTime").HasColumnType("time");
            b.Property<DateTime>("EventDate").HasColumnType("datetime2");
            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");
            b.Property<string>("Location")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("nvarchar(150)");
            b.Property<int>("OrganizerId").HasColumnType("int");
            b.Property<TimeSpan>("StartTime").HasColumnType("time");
            b.Property<string>("Status")
                .IsRequired()
                .HasColumnType("nvarchar(max)");
            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("nvarchar(150)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("Venue")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("nvarchar(150)");

            b.HasKey("Id");
            b.HasIndex("OrganizerId");
            b.ToTable("Events");
        });

        modelBuilder.Entity("KMC.Api.Entities.Payment", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                b.Property<int>("Id"));

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("decimal(18,2)");
            b.Property<string>("CardBrand")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("nvarchar(30)");
            b.Property<string>("CardHolderName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");
            b.Property<string>("CardLastFour")
                .IsRequired()
                .HasMaxLength(4)
                .HasColumnType("nvarchar(4)");
            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("nvarchar(3)");
            b.Property<DateTime>("PaidAt").HasColumnType("datetime2");
            b.Property<DateTime?>("RefundedAt").HasColumnType("datetime2");
            b.Property<int>("RegistrationId").HasColumnType("int");
            b.Property<string>("Status")
                .IsRequired()
                .HasColumnType("nvarchar(max)");
            b.Property<string>("TransactionReference")
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnType("nvarchar(60)");

            b.HasKey("Id");
            b.HasIndex("RegistrationId").IsUnique();
            b.HasIndex("TransactionReference").IsUnique();
            b.ToTable("Payments");
        });

        modelBuilder.Entity("KMC.Api.Entities.Registration", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                b.Property<int>("Id"));

            b.Property<int>("EventId").HasColumnType("int");
            b.Property<int>("ParticipantId").HasColumnType("int");
            b.Property<DateTime>("RegisteredAt").HasColumnType("datetime2");
            b.Property<string>("Status")
                .IsRequired()
                .HasColumnType("nvarchar(max)");
            b.Property<int>("TicketTierId").HasColumnType("int");

            b.HasKey("Id");
            b.HasIndex("ParticipantId");
            b.HasIndex("TicketTierId");
            b.HasIndex("EventId", "ParticipantId").IsUnique();
            b.ToTable("Registrations");
        });

        modelBuilder.Entity("KMC.Api.Entities.TicketTier", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                b.Property<int>("Id"));

            b.Property<int>("Capacity").HasColumnType("int");
            b.Property<int>("EventId").HasColumnType("int");
            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnType("nvarchar(60)");
            b.Property<decimal>("Price")
                .HasPrecision(18, 2)
                .HasColumnType("decimal(18,2)");
            b.Property<int>("SortOrder").HasColumnType("int");

            b.HasKey("Id");
            b.HasIndex("EventId", "Name").IsUnique();
            b.ToTable("TicketTiers");
        });

        modelBuilder.Entity("KMC.Api.Entities.User", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("nvarchar(150)");
            b.Property<string>("FullName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");
            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("nvarchar(max)");
            b.Property<string>("Role")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("KMC.Api.Entities.Event", b =>
        {
            b.HasOne("KMC.Api.Entities.User", "Organizer")
                .WithMany("OrganizedEvents")
                .HasForeignKey("OrganizerId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Organizer");
        });

        modelBuilder.Entity("KMC.Api.Entities.Payment", b =>
        {
            b.HasOne("KMC.Api.Entities.Registration", "Registration")
                .WithOne("Payment")
                .HasForeignKey("KMC.Api.Entities.Payment", "RegistrationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Registration");
        });

        modelBuilder.Entity("KMC.Api.Entities.Registration", b =>
        {
            b.HasOne("KMC.Api.Entities.Event", "Event")
                .WithMany("Registrations")
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("KMC.Api.Entities.User", "Participant")
                .WithMany("Registrations")
                .HasForeignKey("ParticipantId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("KMC.Api.Entities.TicketTier", "TicketTier")
                .WithMany("Registrations")
                .HasForeignKey("TicketTierId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Event");
            b.Navigation("Participant");
            b.Navigation("TicketTier");
        });

        modelBuilder.Entity("KMC.Api.Entities.TicketTier", b =>
        {
            b.HasOne("KMC.Api.Entities.Event", "Event")
                .WithMany("TicketTiers")
                .HasForeignKey("EventId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Event");
        });

        modelBuilder.Entity("KMC.Api.Entities.Event", b =>
        {
            b.Navigation("Registrations");
            b.Navigation("TicketTiers");
        });

        modelBuilder.Entity("KMC.Api.Entities.Registration", b =>
        {
            b.Navigation("Payment");
        });

        modelBuilder.Entity("KMC.Api.Entities.TicketTier", b =>
        {
            b.Navigation("Registrations");
        });

        modelBuilder.Entity("KMC.Api.Entities.User", b =>
        {
            b.Navigation("OrganizedEvents");
            b.Navigation("Registrations");
        });
#pragma warning restore 612, 618
    }
}
